baseURL = "https://securefoss.tech/"
languageCode = 'en-us'
title = 'Secure Foss Tech'

[params]
name  = 'Bharath P'

[markup] 
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true
        
    [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
